//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class CinemaTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CinemaTbl()
        {
            this.MovieTbls = new HashSet<MovieTbl>();
        }
    
        public int CinemaId { get; set; }
        public string CinemaAddress { get; set; }
        public string CinemaName { get; set; }
        public string CinemaEmail { get; set; }
        public string CinemaPhoneNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieTbl> MovieTbls { get; set; }
    }
}
