//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTbl
    {
        public int MovieId { get; set; }
        public string MovieTitle { get; set; }
        public Nullable<int> MovieRunTime { get; set; }
        public Nullable<int> CinemaId { get; set; }
    
        public virtual CinemaTbl CinemaTbl { get; set; }
    }
}
